### ISSUE TITLE
Accessing react.test/app goes 404

### ISSUE THREAD

**Issue by Bluefitdev** [mjsarfatti/create-react-app-laravel#1]
### Describe the bug

Hey First of all thanks for the package, It is very useful for our development process. It was okay for us to do yarn start. I followed the wiki, put all my react app inside the `resources/react-app/`, build it, start it, it works on localhost. 

However i'm using laravel valet and want to know the production product, as i was following your wiki, I realise that when I do `yarn build` it will generate `app.blade.php`

I created my route according to the wiki:

```
Route::get('/app{any?}', function () {
    return view('app');
})->where('any', '.*')->name('app');
```

And checked with `php artisan route:list`

However when i go to react.test/app it shows 404 not found, what could possibly go wrong?

Yarn build shows as follow:

```
 11:18:35   yarn build
yarn run v1.19.2
$ react-scripts build
Creating an optimized production build...
Moving index.html to app.blade.php...
Compiled successfully.

File sizes after gzip:

  696.04 KB  public/static/js/2.201af8fa.chunk.js
  136.14 KB  public/static/js/5.c312edf2.chunk.js
  122.61 KB  public/static/js/3.82eae810.chunk.js
  116.25 KB  public/static/css/main.8b3e86b4.chunk.css
  52.26 KB   public/static/js/main.215cae4c.chunk.js
  42.19 KB   public/static/js/6.2ec62092.chunk.js
  15.65 KB   public/static/js/4.07b53652.chunk.js
  14.46 KB   public/static/css/2.dd8ca586.chunk.css
  1.2 KB     public/static/js/runtime-main.4beeba3a.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The public folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s public

Find out more about deployment here:

  https://bit.ly/CRA-deploy

✨  Done in 33.05s.
```

**Comment by robertwt7** [comment]
omg sorry i just realised that the index.php is also deleted in the public folder


>Every time you yarn build the app the entire content Laravel's public folder will be wiped out, and rebuilt sourcing the contents of resources/react-app/src/public. So make sure you back up any file in public you want to preserve, and after installing Create React App Laravel you move those files to resources/react-app/src/public.

I tried to put the index.php at `resources/react-app/src/public` but then it does not get deployed when I did `yarn build`. Does this mean that we have to clone all files every time?

Thanks

**Comment by robertwt7** [comment]
apparently we can preserve public data of laravel by copying in to `/resources/react-app/public` 

I can't do a pull request for the wiki, but you can change it for others

Thank you!
